name: publish

on:
  push:
    branches: [ master ]

jobs:
  sdist:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Setup python3.12
        run: uv python install 3.12

      - name: Resetting git to master
        run: git reset --hard master

      - name: Fetch git tags
        run: git fetch --unshallow --tags || true

      - name: Build package
        run: uv build

      - name: Publishing to pypi
        run: uv publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
